version: 1
type: maven
resolver:
  snapshotRepo: keyshell-snapshot-virtual
  releaseRepo: keyshell-maven-virtual
  serverID: rt-mvn-repo
deployer:
  snapshotRepo: keyshell-snapshot-virtual
  releaseRepo: keyshell-maven-virtual
  serverID: rt-mvn-repo
