version: 1
type: maven
resolver:
  snapshotRepo: maven-snapshot-virtual
  releaseRepo: test-maven2-virtual
  serverID: rt-mvn-repo
deployer:
  snapshotRepo: maven-snapshot-virtual
  releaseRepo: test-maven2-virtual
  serverID: rt-mvn-repo
